spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nba
    username: root
    password: cpf553457177



  data:
    elasticsearch:
      repositories:
        enabled: true


elasticsearch:
  host: localhost
  port: 9200
